Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLineBetweenDefs:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
