# frozen_string_literal: true

#
# Namespace for the Socializer engine
#
module Socializer
  # Namespace for decorators related to the Person model
  class Person
    # Decorators for {Socializer::Person::Employment}
    class EmploymentDecorator < Draper::Decorator
      delegate_all

      # Define presentation-specific methods here. Helpers are accessed through
      # `helpers` (aka `h`). You can override attributes, for example:
      #
      #   def created_at
      #     helpers.tag.span(class: 'time') do
      #       object.created_at.strftime("%a %m/%d/%y")
      #     end
      #   end

      #  Attributes

      # Returns the `ended_on` date formatted using the `:long_ordinal` format if present.
      #
      # @return [String, nil] formatted date string or `nil` when `ended_on` is not set
      #
      # @example
      #   # => "February 20th, 2015"
      def ended_on
        model.ended_on.to_date.to_fs(:long_ordinal) if model.ended_on?
      end

      # Builds an HTML-safe fragment that represents the employment entry.
      # The fragment includes the employer name followed by optional job title,
      # optional job description, and the employment date range. Each piece is
      # separated by a `<br>` tag generated by `helpers.tag.br`.
      #
      # @return [ActiveSupport::SafeBuffer] an HTML-safe string suitable for rendering in views
      #
      # @example
      #   # => "Acme, Inc.<br>Senior Engineer<br>Worked on X<br>February 20th, 2015 - present"
      def formatted_employment
        employment = [content_and_br(content: model.employer_name)]
        employment << job_title_with_br_or_empty
        employment << job_description_with_br_or_empty
        employment << started_on_to_ended_on

        helpers.safe_join(employment)
      end

      # Returns the `started_on` date formatted using the `:long_ordinal` format if present.
      #
      # @return [String, nil] formatted date string or `nil` when `started_on` is not set
      #
      # @example
      #   # => "February 20th, 2015"
      def started_on
        model.started_on.to_date.to_fs(:long_ordinal) if model.started_on?
      end

      # Returns a formatted date range from `started_on` to `ended_on`.
      # If the employment is current (`current?`), `"present"` is used as the end value.
      #
      # @return [String] formatted date range
      #
      # @example
      #   # => "February 20th, 2015 - present"
      def started_on_to_ended_on
        ended = current? ? "present" : ended_on
        "#{started_on} - #{ended}"
      end

      private

      # Builds an array containing the provided `content` and a `<br>` tag.
      #
      # Returns an Array in the shape expected by `helpers.safe_join` so callers
      # can append it to other fragments and join them into an HTML-safe string.
      #
      # @param content [String] the text content to include before the `<br>` tag
      #
      # @return [Array<String, ActiveSupport::SafeBuffer>] the content and a `<br>` helper
      #
      # @example
      #   content_and_br(content: "Acme, Inc.")
      #   # => ["Acme, Inc.", helpers.tag.br]
      def content_and_br(content:)
        [content, helpers.tag.br]
      end

      # Returns the job title followed by a `<br>` tag when a job title is present.
      #
      # This method returns an Array in the same shape as `content_and_br`
      # (the text content and a `<br>` helper) so callers can pass the result
      # directly to `helpers.safe_join`.
      #
      # @return [Array<String, ActiveSupport::SafeBuffer>, nil] job title and `<br>` tag, or `nil` when absent
      #
      # @example
      #   # => ["Senior Engineer", helpers.tag.br]
      #   job_title_with_br_or_empty
      def job_title_with_br_or_empty
        content_and_br(content: model.job_title) if model.job_title?
      end

      # Returns the job description followed by a `<br>` tag when a job
      # description is present on the model.
      #
      # This method returns an array in the same shape as `content_and_br`
      # (the text content and a `<br>` helper) so callers can pass the result
      # directly to `helpers.safe_join`.
      #
      # @return [Array<String, ActiveSupport::SafeBuffer>, nil] description and `<br>` tag, or `nil` when absent
      #
      # @example
      #   # => ["Worked on X", helpers.tag.br]
      #   job_description_with_br_or_empty
      def job_description_with_br_or_empty
        return unless model.job_description?

        content_and_br(content: model.job_description)
      end
    end
  end
end
